// Code generated by the multiversx-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            7
// Async Callback (empty):               1
// Total number of exported functions:   9

#![no_std]
#![allow(internal_features)]
#![feature(lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    remote_address_validator
    (
        init => init
        addTrustedAddress => add_trusted_address
        removeTrustedAddress => remove_trusted_address
        validateSender => validate_sender
        getRemoteAddress => get_remote_address
        remote_address_hashes => remote_address_hashes
        remote_addresses => remote_addresses
        chainName => chain_name
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
