[package]
name = "gateway-meta"
version = "0.0.0"
edition = "2018"
publish = false
authors = [ "you",]

[dev-dependencies]

[dependencies.gateway]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.47.7"
