// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                            6
// Async Callback (empty):               1
// Promise callbacks:                    1
// Total number of exported functions:  10

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    interchain_token_service_proxy
    (
        init => init
        upgrade => upgrade
        executeWithInterchainToken => execute_with_interchain_token
        setMinGasForExecution => set_min_gas_for_execution
        interchainTokenService => interchain_token_service
        contractAddress => contract_address
        minGasForExecution => min_gas_for_execution
        failedCalls => failed_calls
        execute_callback => execute_callback
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
