// Code generated by the multiversx-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           36
// Async Callback:                       1
// Total number of exported functions:  38

#![no_std]

// Configuration that works with rustc < 1.73.0.
// TODO: Recommended rustc version: 1.73.0 or newer.
#![feature(lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    interchain_token_service
    (
        init => init
        setInterchainTokenFactory => set_interchain_token_factory
        deployTokenManager => deploy_token_manager
        deployInterchainToken => deploy_interchain_token
        expressExecute => express_execute_endpoint
        interchainTransfer => interchain_transfer
        callContractWithInterchainToken => call_contract_with_interchain_token
        setFlowLimits => set_flow_limits
        execute => execute
        interchainTokenId => interchain_token_id
        contractCallValue => contract_call_value
        interchainTokenFactory => interchain_token_factory
        chainNameHash => chain_name_hash
        transferOperatorship => transfer_operatorship
        proposeOperatorship => propose_operatorship
        acceptOperatorship => accept_operatorship
        isOperator => is_operator
        getAccountRoles => account_roles
        getProposedRoles => proposed_roles
        setTrustedAddress => set_trusted_address
        removeTrustedAddress => remove_trusted_address
        chainName => chain_name
        trustedAddress => trusted_address
        trustedAddressHash => trusted_address_hash
        flowLimit => flow_limit
        flowOutAmount => flow_out_amount
        flowInAmount => flow_in_amount
        validTokenManagerAddress => valid_token_manager_address
        validTokenIdentifier => valid_token_identifier
        invalidTokenManagerAddress => invalid_token_manager_address
        gateway => gateway
        gasService => gas_service
        tokenManagerAddress => token_manager_address
        tokenManagerImplementation => token_manager
        pause => pause_endpoint
        unpause => unpause_endpoint
        isPaused => paused_status
    )
}

multiversx_sc_wasm_adapter::async_callback! { interchain_token_service }
