// Code generated by the multiversx-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           11
// Async Callback (empty):               1
// Total number of exported functions:  13

#![no_std]

// Configuration that works with rustc < 1.73.0.
// TODO: Recommended rustc version: 1.73.0 or newer.
#![feature(lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    token_manager_lock_unlock
    (
        init => init
        interchainTransfer => interchain_transfer
        callContractWithInterchainToken => call_contract_with_interchain_token
        giveToken => give_token
        takeToken => take_token
        setFlowLimit => set_flow_limit
        tokenId => token_id
        operator => operator
        tokenAddress => token_address
        get_flow_out_amount => get_flow_out_amount
        get_flow_in_amount => get_flow_in_amount
        getFlowLimit => flow_limit
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
