// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           11
// Async Callback (empty):               1
// Total number of exported functions:  13

#![no_std]
#![allow(internal_features)]
#![feature(lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    governance
    (
        init => init
        executeProposal => execute_proposal
        withdraw => withdraw
        execute => execute
        getProposalEta => get_proposal_eta
        gateway => gateway
        minimum_time_lock_delay => minimum_time_lock_delay
        governance_chain => governance_chain
        governance_address => governance_address
        governance_chain_hash => governance_chain_hash
        governance_address_hash => governance_address_hash
        time_lock_eta => time_lock_eta
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
