// Code generated by the multiversx-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            5
// Async Callback (empty):               1
// Total number of exported functions:   7

#![no_std]

// Configuration that works with rustc < 1.73.0.
// TODO: Recommended rustc version: 1.73.0 or newer.
#![feature(lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    auth
    (
        init => init
        validateProof => validate_proof
        transferOperatorship => transfer_operatorship
        epoch_for_hash => epoch_for_hash
        hash_for_epoch => hash_for_epoch
        current_epoch => current_epoch
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
