// Code generated by the multiversx-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           29
// Async Callback:                       1
// Total number of exported functions:  31

#![no_std]

// Configuration that works with rustc < 1.73.0.
// TODO: Recommended rustc version: 1.73.0 or newer.
#![feature(lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    token_manager
    (
        init => init
        addFlowLimiter => add_flow_limiter
        removeFlowLimiter => remove_flow_limiter
        setFlowLimit => set_flow_limit
        giveToken => give_token
        takeToken => take_token
        deployInterchainToken => deploy_interchain_token
        mint => mint
        burn => burn
        getImplementationTypeAndTokenIdentifier => get_implementation_type_and_token_identifier
        isFlowLimiter => is_flow_limiter
        params => params
        invalidTokenIdentifier => invalid_token_identifier
        interchainTokenService => interchain_token_service
        implementationType => implementation_type
        interchainTokenId => interchain_token_id
        tokenIdentifier => token_identifier
        flowOutAmount => get_flow_out_amount
        flowInAmount => get_flow_in_amount
        getFlowLimit => flow_limit
        transferOperatorship => transfer_operatorship
        proposeOperatorship => propose_operatorship
        acceptOperatorship => accept_operatorship
        isOperator => is_operator
        getAccountRoles => account_roles
        getProposedRoles => proposed_roles
        transferMintership => transfer_mintership
        proposeMintership => propose_mintership
        acceptMintership => accept_mintership
        isMinter => is_minter
    )
}

multiversx_sc_wasm_adapter::async_callback! { token_manager }
