// Code generated by the multiversx-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           11
// Async Callback (empty):               1
// Total number of exported functions:  13

#![no_std]
#![allow(internal_features)]
#![feature(lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    gas_service
    (
        init => init
        payGasForContractCall => pay_gas_for_contract_call
        payNativeGasForContractCall => pay_native_gas_for_contract_call
        payGasForExpressCall => pay_gas_for_express_call
        payNativeGasForExpressCall => pay_native_gas_for_express_call
        addGas => add_gas
        addNativeGas => add_native_gas
        addExpressGas => add_express_gas
        addNativeExpressGas => add_native_express_gas
        collectFees => collect_fees
        refund => refund
        gas_collector => gas_collector
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
