// Code generated by the multiversx-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           13
// Async Callback (empty):               1
// Total number of exported functions:  15

#![no_std]

// Configuration that works with rustc < 1.73.0.
// TODO: Recommended rustc version: 1.73.0 or newer.
#![feature(lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    gas_service
    (
        init => init
        payGasForContractCall => pay_gas_for_contract_call
        payGasForContractCallWithToken => pay_gas_for_contract_call_with_token
        payNativeGasForContractCall => pay_native_gas_for_contract_call
        payNativeGasForContractCallWithToken => pay_native_gas_for_contract_call_with_token
        payGasForExpressCallWithToken => pay_gas_for_express_call_with_token
        payNativeGasForExpressCallWithToken => pay_native_gas_for_express_call_with_token
        addGas => add_gas
        addNativeGas => add_native_gas
        addExpressGas => add_express_gas
        addNativeExpressGas => add_native_express_gas
        collectFees => collect_fees
        refund => refund
        gas_collector => gas_collector
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
